import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { auth } from "@/auth";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/sonner";
import ReduxProvider from "@/store/ReduxProvider";
import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Maidaan",
  description: "Generated by create next app",
};

// const FoundersGrotesk = localFont({
//   // src: "/fonts/FoundersGrotesk-Regular.otf",
//   src: "test.otf",
// });

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={inter.className}>
          <Toaster />
          <ReduxProvider>{children}</ReduxProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
